CONFIG_ZMK_BLE=y
CONFIG_ZMK_USB=y
CONFIG_ZMK_KEYBOARD_NAME="Chofu_pinkchan"

CONFIG_ZMK_LOG_LEVEL_DBG=y
CONFIG_ZMK_KSCAN_LOG_LEVEL_DBG=y
CONFIG_USE_SEGGER_RTT=y
CONFIG_RTT_CONSOLE=y
CONFIG_LOG_BACKEND_RTT=y
CONFIG_LOG_BACKEND_UART=n
